#!/usr/bin/env python

import argparse

from met_jobs.database import Database

parser = argparse.ArgumentParser(
    description="Scrape the met-jobs website and create a database of job ads."
)
parser.add_argument(
    "path_out", metavar="PATH_OUT", type=str, help="The output path for the database"
)
parser.add_argument(
    "-n", "--n_lines_max", default=None, type=int, help="Number of results displayed"
)
parser.add_argument(
    "-v",
    "--verbose",
    action="store_true",
    help="Print retrieved results in real-time as they are found",
)
args = parser.parse_args()

db = Database(args.n_lines_max, args.verbose)
db.to_csv(args.path_out)
